version: '2'

services:
  nginx:
    image: nginx
    container_name: "laravel-nginx"
    ports:
      - "8080:80"
    volumes:
      - ./src:/src
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    links:
     - php
  php:
    build: 
     context: ./php
     dockerfile: Dockerfile
    container_name: "laravel-php" 
